home:
  rails_link: "https://www.railstutorial.org/"
help:
  rails_link: "https://www.railstutorial.org/help"
about:
  rails_link: "https://www.railstutorial.org/"
  learn_enough_link: "https://www.railstutorial.org/"
