footer:
  rails_link: https://www.railstutorial.org/
  author_path: https://www.michaelhartl.com/
home:
  rails_link: https://www.railstutorial.org/
help:
  rails_link: https://www.railstutorial.org/help
about:
  rails_link: https://www.railstutorial.org/
  learn_enough_link: https://www.railstutorial.org/
contact:
  rails_link: https://www.railstutorial.org/contact
regex:
  name_max_length: 255
  email_max_length: 255
  password_min_length: 6
  gravatar_size: 80
  users_gravatar_size: 50
checkbox:
  checked: "1"
paginate:
  pages: 10
